source "https://rubygems.org"
ruby "2.2.3"

gem "ruboty-slack_rtm"
gem "ruboty-kokodeikku"
gem "ruboty-google_image"
gem "ruboty-cron"
gem "ruboty-echo"
gem "ruboty-alias"
gem "ruboty-lgtm"
gem "ruboty-syoboi_calendar"
gem "ruboty-weather"
gem "ruboty-ruby"
gem "ruboty-amagumo" :git => "https://github.com/mausu/ruboty-amagumo.git"
